### ISSUE TITLE
Using Vue Bind Directive with variables breaks the code.

### ISSUE THREAD

**Issue by cs3vigny** [Jacobs63/vue3-tabs-component#48]
When you try to use a variable for the tab name like this:

<tab :name="hitNotesTabName">

You get a library error:

ERROR
Cannot read properties of null (reading 'toLowerCase')
TypeError: Cannot read properties of null (reading 'toLowerCase')
    at setup (webpack-internal:///./node_modules/vue3-tabs-component/dist/vue3-tabs-component.mjs:29:167)
    at callWithErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:296:18)
    at setupStatefulComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:7347:25)
    at setupComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:7308:36)
    at mountComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5712:7)
    at processComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5678:9)
    at patch (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5166:11)
    at mountChildren (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5410:7)
    at processFragment (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5625:7)
    at patch (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5140:9)

**Comment by Jacobs63** [comment]
Hello,

the `name` prop is required as a string, so you should pass a string to it.

This is not a bug in the package.

**Comment by cs3vigny** [comment]
Failing to make things reactive and dynamic in a VUE package which prides itself on being reactive and dynamic is not good. Your idea is sound and the main functionality is good, but failing on the most basic of VUE concepts is going to make this package fail in terms of it's usability unfortunately. Something you should consider and think about. Thank you.  Keep coding my man!

-EDIT- This was my bad. The developer responded and while I would expect better error handling, this library appears to work well. Thank you.

**Comment by Jacobs63** [comment]
Props are reactive by-default. Again, passing `null` to a prop of type `string` is clearly a bug on your side.

I'll not react to the rest as I'm not sure what this rant is about.

**Comment by cs3vigny** [comment]
Ah, that is caused by a null value? Gotcha. my bad. Ignore my previous comment.

**Comment by cs3vigny** [comment]
Awesome, that was it. It was null on render and then afterwards was updated and works well. As a developer I expected that your library would check for null and handle it gracefully instead of crashing the entire page, but I suppose that is up to you as the designer. Thank you for responding!

**Comment by Jacobs63** [comment]
I'll give you an example from the official Vue Router - https://github.com/vuejs/router/blob/main/packages/router/src/RouterView.ts

Coincidentally, it doesn't check for the type of `name` either.
